fix: Always fetch derivation closure when max-jobs == 0
This solves an instance of

    error: unable to start any build; remote machines may not have all
required system features.

In this situation, the optimization to resolve without a full closure
leads to a strange error in the Nix scheduler, as the optimization
should not be applied.