Work around missing C++ symbol on darwin
Solves:

    Linking dist/build/hercules-ci-agent-worker/hercules-ci-agent-worker ...
    Undefined symbols for architecture x86_64:
      "HerculesLogger::HerculesLogger()", referenced from:
          _inline_c_Hercules_Agent_Worker_Build_Logger_0 in Logger.o
    ld: symbol(s) not found for architecture x86_64
    clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
    `cc' failed in phase `Linker'. (Exit code: 1)